# Tasks for git role
---
# this shows available facts
- name: Show facts available on the system
  ansible.builtin.debug:
    #msg: "Hello, world!"
    var: ansible_facts

- name: install git - APT
  apt: name=git
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: install git - YUM
  yum: name=git
  when: ansible_facts['pkg_mgr'] == 'yum'

- name: install misc git scripts
  template: src={{ item }}.j2 dest=/usr/local/bin/{{ item }}
            owner=root group=root mode=0755
  with_items:
    - graph_log.sh
    - git_remote_status.sh
    - push_branch.sh

